export const ADD_ROW = 'ADD_ROW';
export const DELETE_ROW = 'DELETE_ROW';
export const UPDATE_ROW_STATUS = 'UPDATE_ROW_STATUS';
export const TOGGLE_ROWS_STATUS = 'TOGGLE_ROWS_STATUS';
export const DELETE_COMPLETED_ROWS = 'DELETE_COMPLETED_ROWS';
export const SET_SELECTED_ROW = 'SET_SELECTED_ROW';