export const ADD_ROW = 'ADD_ROW';
export const DELETE_ROW = 'DELETE_ROW';
export const UPDATE_ROW_STATUS = 'UPDATE_ROW_STATUS';
export const UPDATE_ROW_DESCRIPTION = 'UPDATE_ROW_DESCRIPTION';
export const TOGGLE_ROWS_STATUS = 'TOGGLE_ROWS_STATUS';
export const DELETE_COMPLETED_ROWS = 'DELETE_COMPLETED_ROWS';

export const SET_LOCAL_STORAGE_REQUEST = 'SET_LOCAL_STORAGE_REQUEST';
export const SET_LOCAL_STORAGE_SUCCESS = 'SET_LOCAL_STORAGE_SUCCESS';
export const SET_LOCAL_STORAGE_FAILURE = 'SET_LOCAL_STORAGE_FAILURE';

export const GET_LOCAL_STORAGE_REQUEST = 'GET_LOCAL_STORAGE_REQUEST';
export const GET_LOCAL_STORAGE_SUCCESS = 'GET_LOCAL_STORAGE_SUCCESS';
export const GET_LOCAL_STORAGE_FAILURE = 'GET_LOCAL_STORAGE_FAILURE';

export const DESCRIPTION_EXAMPLE = 'DESCRIPTION_EXAMPLE';
export const TO_DO = 'TO_DO';

export const CLEAR_REDIRECT_TO = 'CLEAR_REDIRECT_TO';